### PR TITLE
fix: remove role binding to legacy service account  name

### LINKED ISSUE #1005: Remove legacy rolebinding from `build_rbac_resources`
#909 changed `build_rbac_resources` to use the stacklet name rather than product name, but we still kept the old format in the binding to prevent outages during upgrades.

It should be removed after a grace period. (The comment says v24.3+1, but looking at the dates v25.3+1 would make more sense..)

### PR DESCRIPTION
**Pull request by razvan**
# Description

Fixes #1005
## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

### Author

- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] CRD documentation for all fields, following the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [ ] Integration tests passed (for non trivial changes)
- [ ] Changes need to be "offline" compatible

### Reviewer

- [ ] Code contains useful comments
- [ ] Code contains useful logging statements
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)

### Acceptance

- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added

### CODE REVIEW

File: crates/stackable-operator/src/commons/rbac.rs [hunk 1]
```diff
@@ -28,24 +28,18 @@ pub enum Error {
...
+/// The service account is bound to a cluster role named `{product_name}-clusterrole` which
+/// must already exist.
 pub fn build_rbac_resources<T: Clone + Resource<DynamicType = ()>>(
     resource: &T,
-    // 'product_name' is not used to build the names of the serviceAccount and roleBinding objects,
-    // as this caused problems with multiple clusters of the same product within the same namespace
-    // see <https://stackable.atlassian.net/browse/SUP-148> for more details.
-    // Instead the names for these objects are created by reading the name from the cluster object
-    // and appending [-rolebinding|-serviceaccount] to create unique names instead of using the
-    // same objects for multiple clusters.
```
Comment (nightkr) [inline crates/stackable-operator/src/commons/rbac.rs:40]: I think this comment still makes sense tbh (as internal motivation for why things are the way they are).

**Review by nightkr — COMMENTED** [review]
LGTM otherwise

File: crates/stackable-operator/src/commons/rbac.rs (hunk 1 above)
Comment (razvan) [reply crates/stackable-operator/src/commons/rbac.rs:40]: Indeed. [Readded](https://github.com/stackabletech/operator-rs/pull/1060/commits/f27dec51dcbf11fa365009d00ad4082b3fa031d2)

**Review by nightkr — APPROVED** [review]

**Comment by lfrancke** [comment]
Should this appear in the release notes?
